### ISSUE TITLE
TransactionOutput deserialisation issues

### ISSUE THREAD

**Issue by omefire** [dcSpark/carp#115]
I recently (approx. 17 days ago) launched Carp on a server and had it sync against the blockchain/Oura.

I want to deserialise the payload in the TransactionOutput table to the TransactionOutput class in Typescript/Javascript using the library `https://www.npmjs.com/package/@dcspark/cardano-multiplatform-lib-nodejs`.

However, I keep getting an error `Variant not found`.
Interestingly, I can successfully deserialise an object like TransactionMetadata from it's payload in the Carp db.

I was wondering if there's been a change to the way that TransactionOutput is being serialized? (that ends up throwing off deserialisation)?

Also,if the answer to the first question is 'Yes', what version of the npm package should I use that is compatible with the latest serialisation format of TransactionOutput?

**Comment by SebastienGllmt** [comment]
If you're using the latest version of multiplatform-lib, it should work

Keep in mind that Byron (very old outputs) are a different type than everything after Shelley so the type is different for that one

**Comment by omefire** [comment]
Ooh, I see. Didn't know that. Trying out with outputs from more recent epochs/blocks.
Will let you know.

Thanks!

**Comment by omefire** [comment]
Btw, where is the TransactionOutput serialisation code located? Is that automatically handled by serde's serialisation lib? Any specific advice if one wants to deserialise it using another library? (custom one, maybe another language). Is it cbor?

**Comment by omefire** [comment]
I just tried deserialising this, and it still failed:

`82584c82d818584283581cceb6369411755dcd25a28c08b11d2b1c90a1503e4cbc12ac324d0c76a101581e581c2b0b011ba3683d6c65c3ef2a7a3ff08e39a526fae99d163c4b038331001a2a3ac8661a7a308480`

**Comment by SebastienGllmt** [comment]
@omefire what is the transaction hash this output belongs to?

**Comment by omefire** [comment]
Transaciton payload: \x84a500828258200147c4657d86232ee93777dad5c6008b4f541a05aa6c2cebd9099f81e2496970018258209d0dde8c785534db15bc58a9764fe2d11c01de7c8a4e1da19642e2a1d7060dfe01018283581d714a59ebd93ea53d1bbf7f82232c7b012700a0cf4bb78d879dabb1a20a821a001cd277a1581ca5bb0e5bb275a573d744a021f9b3bff73595468e002755b447e01559a156484f534b594361736847726162303030303237383730015820577e10ec0580b6056c50cbdc9efbf8a64414549d1341520170139f494c4d790582583901568df7b66d34c998c1106241d502d905a550314f8a9b11397f8444862bf217ee86f7975e7a11b0df4c07155ef19a7a25881632bb383d5e62821a05b3d5bfa2581c0d27ee4630ee8a9e62664ccd8e61fc43a62699ae28f3718b4a66a36ba14e50657273697374656e636539343801581ce30726d8b91be8e8f3860db0eaccfa6b7c038b2a13bfd8e3df18b9bba14b5061636b436f696e32323401021a00033da7031a0329f6f90758207f7b854a91e18fd09eee3ad063d28944a58147da483a7e484abf5e80aecee0f4a100818258206e8596ba9abdd0f7306d6de68613a076b18594d98a92d7e63ec44a0d1f56a3ac584004bfac722ba3fbe8437461614039a9d52990e6e580c106666293d5fa2c320386233b0b5229f0bbc220636733beff3884adca410672c5b6612c6d8cbdb8185609f5a800783835363864663762363664333463393938633131303632343164353032643930356135353033313466386139623131333937663834343438360167383030303030300278386634346638373531663033643736376261353163346665393838656432383962376365643463376538333232323364343462333162636365036231300678406164647231713974676d61616b643536766e7878707a7033797234677a6d797a3632357033663739666b79666530377a796670337437677437617068686a613007782738357964736d6178717739323737786438356676677a6365746b77706174653371646d777532370878406164647231713836796c7036333771376876376139723338376e7a3864397a6468656d32763036706a796737356676636d656e337267387434713366383072350978273670393378717a686375703077376535686571376c6e61796a7a716175336466733779726c7335

**Comment by omefire** [comment]
Transaction hash:

`\x52f98f3862f73057a3d7049b6f97d71c5cc2da3d3450583316a1ca0cf7e84cba`

**Comment by SebastienGllmt** [comment]
Are you sure you posted the right bytes for the TransactionOutput?

I see the full transaction payload you posted does give the transaction hash you provided, but the two outputs for this transaction have a different payload than what you posted

Instead, I get
```
83581d714a59ebd93ea53d1bbf7f82232c7b012700a0cf4bb78d879dabb1a20a821a001cd277a1581ca5bb0e5bb275a573d744a021f9b3bff73595468e002755b447e01559a156484f534b594361736847726162303030303237383730015820577e10ec0580b6056c50cbdc9efbf8a64414549d1341520170139f494c4d7905
```
and
```
82583901568df7b66d34c998c1106241d502d905a550314f8a9b11397f8444862bf217ee86f7975e7a11b0df4c07155ef19a7a25881632bb383d5e62821a05b3d5bfa2581c0d27ee4630ee8a9e62664ccd8e61fc43a62699ae28f3718b4a66a36ba14e50657273697374656e636539343801581ce30726d8b91be8e8f3860db0eaccfa6b7c038b2a13bfd8e3df18b9bba14b5061636b436f696e32323401
```

**Comment by omefire** [comment]
I did change to a different TransactionOutput when looking for one that is more recent. 
The TransactionOutput I posted belongs to a Transaction that happened more recently, and it still fails to deserialise.
In addition, the two outputs you posted also fail to deserialise.

**Comment by SebastienGllmt** [comment]
It seems to deserialize fine for me

```rust
TransactionOutput::from_bytes(
    hex::decode(
        "83581d714a59ebd93ea53d1bbf7f82232c7b012700a0cf4bb78d879dabb1a20a821a001cd277a1581ca5bb0e5bb275a573d744a021f9b3bff73595468e002755b447e01559a156484f534b594361736847726162303030303237383730015820577e10ec0580b6056c50cbdc9efbf8a64414549d1341520170139f494c4d7905"
    ).unwrap()
).unwrap();
```

**Comment by omefire** [comment]
I used the following code (Typescript):

```

let txOutStr: string = "83581d714a59ebd93ea53d1bbf7f82232c7b012700a0cf4bb78d879dabb1a20a821a001cd277a1581ca5bb0e5bb275a573d744a021f9b3bff73595468e002755b447e01559a156484f534b594361736847726162303030303237383730015820577e10ec0580b6056c50cbdc9efbf8a64414549d1341520170139f494c4d7905";

let txOut = wasm.TransactionOutput.from_bytes(Buffer.from(txOutStr));
```

**Comment by SebastienGllmt** [comment]
```typescript
wasm.TransactionOutput.from_bytes(Buffer.from(txOutStr, 'hex'));
```

If you don't specify hex, it will try and parse the string as utf8

**Comment by omefire** [comment]
Haha, thanks very much!

**Comment by omefire** [comment]
Strange that it did work for other types like Metadata, hmmm
