### ISSUE TITLE
Restoring from a backup or snapshot?

### ISSUE THREAD

**Issue by jeremybarnes2342** [dcSpark/carp#151]
Is there any way you guys can provide instructions on how to restore Cardano Node from a snapshot? Is there an easy way to do this with Carp + Docker?

Thanks!

**Comment by SebastienGllmt** [comment]
For anything cardano-node related you'll have to look at the cardano-node documentation. From Carp's perspective, we do have a backup system explained in our docs
https://dcspark.github.io/carp/docs/indexer/docker#backup-service
