### ISSUE TITLE
Epoch not match with block number while index preview 

### ISSUE THREAD

**Issue by ironmask285** [dcSpark/carp#160]
I have synced data from preview. But I see epoch not match with block number, you can check my logs 
```
id    era    hash    height    epoch    slot    payload
21618    5    binary data    21616    1    432019    binary data
```
It isn't true. Height 21616 in Epoch 5 ( you can check at here https://preview.cardanoscan.io/block/21616) . I don't got it. please help

**Comment by SebastienGllmt** [comment]
I suspect it’s a mismatch between the network type and the length of an epoch

On mainnet, epochs are 21600 blocks, but on preview they are shorter

**Comment by ironmask285** [comment]
yah, I thinks so. But Do you have any idea to resolve it? please help

**Comment by SebastienGllmt** [comment]
looks like this comes from oura: https://github.com/txpipe/oura/blob/e0d16a47a8213a07424d7dcdfe78ea1186bd90f5/src/utils/mod.rs#L117

It seems to work fine if I manually patch Oura:
```
    if network == "preview" {
        well_known.shelley_epoch_length = 86400;
    }
```
You can see this in the Oura repo here: [mod.rs](https://github.com/txpipe/oura/blob/e0d16a47a8213a07424d7dcdfe78ea1186bd90f5/src/utils/mod.rs)

**Comment by ironmask285** [comment]
thanks so much
