### ISSUE TITLE
Indexer Sanchonet: couldn't find a starting point in the node's current branch

### ISSUE THREAD

**Issue by ironmask285** [dcSpark/carp#192]
I setup indexer for sanchonet. But I get issue 
`2024-05-20T06:55:31.224103Z  WARN request handler:block_fetch{from=[BlockHeader { slot_nb: SlotNumber(0), hash: BlockId("785eb88427e136378a15b0a152a8bfbeec7a611529ccda29c43a1e60ffb48eaa") }] last_tip_event=Instant { tv_sec: 3337242, tv_nsec: 375192453 } tip_update_pace=5s network_config=NetworkConfiguration { chain_info: NetworkInfo { network_id: 1, protocol_magic: ProtocolMagic(4) }, relay: ("localhost", 6001), from: BlockHeader { slot_nb: SlotNumber(0), hash: BlockId("785eb88427e136378a15b0a152a8bfbeec7a611529ccda29c43a1e60ffb48eaa") }, genesis_parent: BlockId("6a7d97aae2a65ca790fd14802808b7fce00a3362bd7b21c4ed4ccb4296783b98"), genesis: BlockId("6a7d97aae2a65ca790fd14802808b7fce00a3362bd7b21c4ed4ccb4296783b98"), shelley_era_config: Era { first_slot: 0, start_epoch: 0, known_time: 1686789000, slot_length: 1, epoch_length_seconds: 86400 } }}: dcspark_blockchain_source::cardano: couldn't find a starting point in the node's current branch tip=1468715-29399106@53cf161b25f5aedad8db60768c36e50483092aa8a1a578561bb1cd81b6bbce43
`
Here's my config 
`source:
   type: cardano_net
   relay:
       - localhost
       - 6000

sink:
  type: cardano
  db:
    type: postgres
    database_url: postgresql://postgres:password@localhost:5432/sanchonet
  network: sanchonet # preview / preprod / testnet/ sanchonet
`

please help me !

**Comment by SebastienGllmt** [comment]
Are you sure the node you're pointing to for the relay is running on sanchonet?

**Comment by ironmask285** [comment]
yah, I checked my node :
{
    "block": 1468823,
    "epoch": 340,
    "era": "Conway",
    "hash": "74ad2e921b6829a8fe4c6a7a1ff7bc7f87e9ab5071841a9823653afc7cb77e12",
    "slot": 29401435,
    "slotInEpoch": 25435,
    "slotsToEpochEnd": 60965,
    "syncProgress": "100.00"
}
and my topology config's : 

`{
  "bootstrapPeers": [
    {
      "address": "sanchonet-node.play.dev.cardano.org",
      "port": 3001
    }
  ],
  "localRoots": [
    {
      "accessPoints": [],
      "advertise": false,
      "trustable": false,
      "valency": 1
    }
  ],
  "publicRoots": [
    {
      "accessPoints": [],
      "advertise": false
    }
  ],
  "useLedgerAfterSlot": 21599922
`
