### ISSUE TITLE
indexed data not match with https://sancho.cexplorer.io/

### ISSUE THREAD

**Issue by ironmask285** [dcSpark/carp#194]
I indexed the Sanchonet network, but I noticed that the hash from block 1,304,463 does not match the data on [sancho.cexplorer.io](https://sancho.cexplorer.io).

### My Indexed Data:
```
Block: 1304494
Slot: 5
Block Data: "binary data"
Previous Block: 1304463
Epoch: 301
Transaction Count: 26092729
Transaction Data: "binary data"
VRF Result: 0
Hash: \xda0c4f19c2a1c9c13ce1aff369198029dbd29156d34b690f1f238e86d638d798
```

### Data from sancho.cexplorer.io:
![Sancho Explorer Data](https://github.com/dcSpark/carp/assets/4832192/594ad7b1-3c63-42a1-8b63-13df2fb7329a)

There are two different hashes. Can you help me resolve this discrepancy?

---

This format clearly presents your issue and includes all necessary details for someone to understand and help you.

**Comment by SebastienGllmt** [comment]
It looks like at the time you created your issue, the cexplorer sanchonet was stuck on a fork and stopped syncing blocks. I tried checking in again to see if the issue persists, but it looks like their sanchonet support is unavailable at the moment
