### ISSUE TITLE
Document minimum requirements

### ISSUE THREAD

**Issue by SebastienGllmt** [dcSpark/carp#51]
I think the current DB is ~130GBs, but I need to double-check and we also need to figure out cpu/ram requirements

**Comment by SebastienGllmt** [comment]
Some other related service stats

57G	mainnet/node-db
4.0K	mainnet/node-ipc
34G	mainnet/postgres-data
8.0K	mainnet/tmp

**Comment by szandala** [comment]
RAM below 16 GBs sometimes crashes `cardano-node`
Also I believe 4+ CPUs are welcome
