### ISSUE TITLE
panicked at 'DeserializeError { location: Some("TransactionBody.outputs.TransactionOutputs.TransactionOutput.address.Address"), failure: CBOR(TrailingData) }

### ISSUE THREAD

**Issue by rinor** [dcSpark/carp#53]
```
2022-05-13T21:01:52.615267Z  INFO carp::postgres_sink: Starting epoch 337 at block #7225024 (ef0388b8fc14ae432f0e7bf606efcf76f301efee6e28e67ae6987669db18d5a5)
thread '<unnamed>' panicked at 'DeserializeError { location: Some("TransactionBody.outputs.TransactionOutputs.TransactionOutput.address.Address"), failure: CBOR(TrailingData) }
Block cbor: "8205..."
Tx hash: "9c1d13c1d2153651c3c8ff1dfeb16e0b9de5f519fa482d1f07d4320e2ab78fd3"
', tasks/src/multiera/multiera_txs.rs:112:21
```
**tx**: https://cardanoscan.io/transaction/9c1d13c1d2153651c3c8ff1dfeb16e0b9de5f519fa482d1f07d4320e2ab78fd3
**block**: https://cardanoscan.io/block/7225024
**full log**: [carp_panic_9c1d13c1d2153651c3c8ff1dfeb16e0b9de5f519fa482d1f07d4320e2ab78fd3.log](https://github.com/dcSpark/carp/files/8691367/carp_panic_9c1d13c1d2153651c3c8ff1dfeb16e0b9de5f519fa482d1f07d4320e2ab78fd3.log)

**Comment by SebastienGllmt** [comment]
This is a known issue that can't be properly fixed until the Vasil hardfork
