### ISSUE TITLE
Error: Could not find task named GenesisBlockTask 

### ISSUE THREAD

**Issue by deniskv** [dcSpark/carp#81]
How to reproduce: Define env variables and run `docker-compose up`. 

> root@8c6a7879c93d:/app# ./carp
> 2022-05-26T21:15:09.694606Z  INFO carp: Starting Carp
> 2022-05-26T21:15:09.694732Z  INFO carp: Execution plan execution_plans/default.toml
> 2022-05-26T21:15:09.694921Z  INFO carp: Connecting to database...
> 2022-05-26T21:15:09.700071Z  INFO carp: Getting the latest block synced from DB
> 2022-05-26T21:15:09.702426Z  INFO carp::genesis: Parsing genesis file...
> 2022-05-26T21:15:09.731066Z  INFO carp::genesis: Finished parsing genesis file after 28.60967ms
> 2022-05-26T21:15:09.731078Z  INFO carp::genesis: Inserting genesis data into database...
> 2022-05-26T21:15:09.731712Z  INFO carp::genesis: Starting sync based on genesis hash 96fceff972c2c06bd3bb5243c39215333be6d56aaf4823073dca31afe5038471
> thread 'main' panicked at 'Could not find task named GenesisBlockTask', /carp/tasks/src/genesis/genesis_executor.rs:32:21
> stack backtrace:
>    0:     0x55ae16f623cc - <unknown>
>    1:     0x55ae16f8876c - <unknown>
>    2:     0x55ae16f5b5b3 - <unknown>
>    3:     0x55ae16f64d42 - <unknown>
>    4:     0x55ae16f64925 - <unknown>
>    5:     0x55ae16f65393 - <unknown>
>    6:     0x55ae16f650b0 - <unknown>
>    7:     0x55ae16f62874 - <unknown>
>    8:     0x55ae16f64de9 - <unknown>
>    9:     0x55ae16b4c611 - <unknown>
>   10:     0x55ae16b96e52 - <unknown>
>   11:     0x55ae16b9b6c6 - <unknown>
>   12:     0x55ae16b92811 - <unknown>
>   13:     0x55ae16b94735 - <unknown>
>   14:     0x55ae16b9d793 - <unknown>
>   15:     0x55ae16b8845c - <unknown>
>   16:     0x55ae16bd274b - <unknown>
>   17:     0x55ae16bdfd4d - <unknown>
>   18:     0x55ae16b690cb - <unknown>
>   19:     0x55ae16b74139 - <unknown>
>   20:     0x55ae16bd5493 - <unknown>
>   21:     0x55ae16b5a93d - <unknown>
>   22:     0x55ae16f61a80 - <unknown>
>   23:     0x55ae16b76352 - <unknown>
>   24:     0x7f5e4b613d0a - __libc_start_main
>   25:     0x55ae16b4ce8a - <unknown>
>   26:                0x0 - <unknown>

**Comment by SebastienGllmt** [comment]
I believe this should be fixed by https://github.com/dcSpark/carp/pull/75
