### ISSUE TITLE
Carp crashes while syncing testnet

### ISSUE THREAD

**Issue by SebastienGllmt** [dcSpark/carp#82]
Seems like an upstream issue in Pallas: https://github.com/txpipe/oura/issues/307

```
tx: 86002c31759d2bea736791c8010f2d7e67fc7dd6032e9f96361c78578b2eabbe
thread '<unnamed>' panicked at 'explicit panic', tasks/src/multiera/multiera_used_inputs.rs:131:21
```

**Comment by deniskv** [comment]
> 2022-05-31T10:43:04.230159Z  INFO carp: Starting sync at block #1598700 (52c8da8db93f503e21f6148b9c2c647cbc68b04717b38ebb163be5a5350b7207)
> 2022-05-31T10:43:04.230192Z  INFO carp::setup: Attempting to connect to node...
> 2022-05-31T10:43:04.230918Z  INFO carp::setup: Connection to node established
> 2022-05-31T10:43:04.231303Z  INFO carp::postgres_sink: Starting to process blocks
> 2022-05-31T10:43:04.240757Z  WARN pallas_multiplexer: protocol handle 0 disconnected    
> 2022-05-31T10:43:04.251437Z  INFO carp::postgres_sink: Rolling back to block 52c8da8db93f503e21f6148b9c2c647cbc68b04717b38ebb163be5a5350b7207 at slot 1598699
> 2022-05-31T10:43:04.261596Z  INFO carp::postgres_sink: Starting epoch 74 at block #1597149 (bc0e595673def5734dff91daac096dbbb4c3a70e292abf41a7853e9006bfb2ec)
> tx: f583154e1af248a2f33efa00f051dbad50d3854c45bd1b4b04d71f26c633da38
> thread '<unnamed>' panicked at 'explicit panic', tasks/src/multiera/multiera_used_inputs.rs:131:21

I have the same problem too.

**Comment by deniskv** [comment]
Any updates?

**Comment by SebastienGllmt** [comment]
@deniskv upstream package got a fix deployed during the weekend. I haven't had time to test it yet, but hopefully it resolves the issue: https://github.com/txpipe/oura/issues/307#issuecomment-1146883980

**Comment by deniskv** [comment]
@SebastienGllmt Thx! I already found it. I have tried to update package version but build fails. Seems like update requires changes in code (Or not. I'm not good in rust). I'll attach build log later.
