### ISSUE TITLE
Vasil Testnet support

### ISSUE THREAD

**Issue by oskin1** [dcSpark/carp#92]
Are there any plans to add Vasil HF support to Carp? Any ETA on this?

**Comment by satutobi** [comment]
How is it going @SebastienGllmt?

**Comment by SebastienGllmt** [comment]
Still stuck on an Oura error partway through Vasil when the Plutus v2 cost model got removed

**Comment by SebastienGllmt** [comment]
The Pallas and Oura issues seemed to be resolved. We managed to sync our node to tip on the Vasil testnet with no issue, so we created a 2.0.0 release
https://github.com/dcSpark/carp/releases/tag/2.0.0
